In [23]:
import numpy as np
import gym
import random

In [ ]:
env = gym.make("FrozenLake")
#env = gym.make('FrozenLake-v1', render_mode='human')  # یا 'ansi' برای خروجی متنی


c:\Users\NovinStore\AppData\Local\Programs\Python\Python311\Lib\site-packages\gym\envs\registration.py:601: UserWarning: WARN: Using the latest versioned environment `FrozenLake-v1` instead of the unversioned environment `FrozenLake`.
  logger.warn(
c:\Users\NovinStore\AppData\Local\Programs\Python\Python311\Lib\site-packages\gym\core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
c:\Users\NovinStore\AppData\Local\Programs\Python\Python311\Lib\site-packages\gym\wrappers\step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [5]:
action_size = env.action_space.n
state_size = env.observation_space.n

print(action_size)
print(state_size)

4
16


In [ ]:
action_size = env.action_space.n
state_size = env.observation_space.n

print(action_size)
print(state_size)

In [6]:
qtable = np.zeros((state_size,action_size))
qtable

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
total_episodes = 100000
learning_rate = 0.8
max_steps = 99
gamma = 0.95

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.01

In [25]:
rewards = []
ic = 0
for episode in range(total_episodes):
    state = env.reset()
    done = False
    total_reward = 0 

    for step in range(max_steps):
        exp_exp_tradeoff = random.uniform(0, 1)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state, :])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        
        qtable[state, action] += learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_reward += reward 
        state = new_state
        
        if done:
            break

    ic += 1
    if ic > 1000:
        ic = 0
        print(episode, total_reward)  
    
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_reward) 

print("Score over time: " + str(sum(rewards) / total_episodes))
print(qtable)

1000 0.0
2001 1.0
3002 0.0


KeyboardInterrupt: 

In [19]:
print(qtable)

[[1.66140993e-01 2.68897889e-02 3.09691809e-02 4.48761400e-02]
 [5.66717522e-04 8.87211903e-03 1.76411331e-03 4.03946884e-02]
 [2.83449714e-03 1.13644837e-02 3.26981013e-02 1.14831443e-02]
 [3.57343140e-03 6.34237904e-03 3.72234879e-03 2.12138408e-02]
 [1.78741732e-01 9.85415856e-03 5.40290175e-02 1.71422483e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.66415812e-04 7.94974520e-06 1.08137153e-01 8.57135240e-11]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.48122571e-02 1.55848641e-02 4.00439928e-02 4.23513849e-01]
 [3.43102087e-02 5.37346046e-01 2.62773903e-02 4.42643153e-02]
 [7.28885413e-01 2.01007596e-02 5.13118949e-03 2.09965523e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.12488466e-02 7.36774834e-02 5.56466125e-01 6.07597188e-02]
 [1.69429217e-01 9.07043026e-01 2.23888876e-01 1.62060575e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

In [ ]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("**********************************")
    print("episode ", episode)

    for step in range(max_steps):
        env.render()
        action = np.argmax(qtable[state,:])

        new_state, reward, done, info = env.step(action)
        if done:
            break
        state = new_state

**********************************
episode  0


c:\Users\NovinStore\AppData\Local\Programs\Python\Python311\Lib\site-packages\gym\core.py:49: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don't call the render method.
See here for more information: https://www.gymlibrary.ml/content/api/
  deprecation(


**********************************
episode  1
**********************************
episode  2
**********************************
episode  3
**********************************
episode  4


: 